### ISSUE TITLE
Adding AOT compilation

### ISSUE THREAD

**Issue by ardera** [Team-CC-Corp/JVML-JIT#69]
Programs that use JVML-JIT are unportable, because computers wanting to run them must have JVML-JIT installed. Adding AOT Compilation (Ahead of Time Compilation) to compile your classes and resources into a lua program would make them more portable and faster. Also, it's not that hard to implement. What do you think?

**Comment by ElvishJerricco** [comment]
* We already have an [issue thread](https://github.com/Team-CC-Corp/JVML-JIT/issues/62) for this.
* It is that difficult, as outlined in the original thread

**Comment by ardera** [comment]
Sorry, I didn't see the other issue, and I didn't know it was that hard to implement.
